apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 80
  selector:
    app: grafana
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gf-pv-claim
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: frontend
    spec:
      containers:
      - image: docker.io/grafana/grafana:5.3.2
        name: grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: influxdb-pass
              key: GF_SECURITY_ADMIN_USER
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-pass
              key: GF_SECURITY_ADMIN_PASSWORD
        ports:
        - containerPort: 80
          name: grafana
        volumeMounts:
        - name: gf-persistent-storage
          mountPath: /var/www/html
        - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yml
          name: grafana-config
          readOnly: true
          subPath: influxdb-datasource.yml
        - mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yml
          name: grafana-config
          readOnly: true
          subPath: grafana-dashboard-provider.yml
        - mountPath: /var/lib/grafana/dashboards/grafana_dashboard.json
          name: grafana-config
          readOnly: true
          subPath: grafana_dashboard.json
      volumes:
      - name: gf-persistent-storage
        persistentVolumeClaim:
          claimName: gf-pv-claim
      - configMap:
          name: grafana-config
        name: grafana-config
