apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name localhost www.localhost;
      root /usr/share/nginx/html;
      location /wordpress {
        proxy_read_timeout 3600;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header Host $http_host;
        proxy_pass http://wordpress-service;
      }
      location /phpmyadmin{
        proxy_read_timeout 3600;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:5000;
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  ports:
    - name: grafana
      port: 3000
      targetPort: 80
  selector:
    app: grafana
    tier: frontend
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gf-pv-claim
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: frontend
    spec:
      containers:
      - image: docker.io/grafana/grafana:5.3.2
        name: grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: influxdb-pass
              key: GF_SECURITY_ADMIN_USER
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-pass
              key: GF_SECURITY_ADMIN_PASSWORD
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: gf-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: gf-persistent-storage
        persistentVolumeClaim:
          claimName: gf-pv-claim
