apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name localhost www.localhost;
      root /usr/share/nginx/html;
      location /wordpress {
        proxy_read_timeout 3600;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header Host $http_host;
        proxy_pass http://wordpress-service;
      }
      location /phpmyadmin{
        proxy_read_timeout 3600;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:5000;
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
#            - containerPort: 443
          volumeMounts:
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-volume
          configMap:
            name: nginx-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
#    - port: 443
 #     name: https
  #    protocol: TCP
  selector:
    app: nginx