#!/bin/sh

# users:
# - usagi:usagi
# - cchudant:licorne
# - dieu:trbonnes
# - nobody:anybody

MYSQL="mysql -h $WORDPRESS_DB_HOST -u $WORDPRESS_DB_USER --password=$WORDPRESS_DB_PASSWORD"

# crash if connection error
$MYSQL -e '' || exit 1

echo "creation database"
$MYSQL -e 'CREATE DATABASE wordpress_db;' ||
		( $MYSQL -e 'DROP DATABASE wordpress_db;'; conn_error)
echo "importation database"
$MYSQL wordpress_db < /wordpress_db.sql ||
		( $MYSQL -e 'DROP DATABASE wordpress_db;'; conn_error)
echo "database imported"

sed -i 's/^exec .*//' /usr/local/bin/docker-entrypoint.sh
docker-entrypoint.sh php-fpm

/usr/sbin/nginx && /usr/local/sbin/php-fpm
